### ISSUE TITLE
it not work with jetson, plz upgrade

### ISSUE THREAD

**Issue by tienhoang1094** [koenvervloesem/tensorflow-addons-on-arm#1]
thanks

**Comment by koenvervloesem** [comment]
I don't have a Jetson Nano board, so I can't test this. Can you be more specific than "it not work"? What error message do you get?

**Comment by tienhoang1094** [comment]
i dont remember, but it about this kinda wheel not appropriate for my os. i try install it from source tf_addons offical, it work!
