### ISSUE TITLE
There is a problem executing make tfa

### ISSUE THREAD

**Issue by karmalk** [koenvervloesem/tensorflow-addons-on-arm#2]
Hello, I am sorry to trouble you, my bazel has been installed, as shown below
`root@b39582782284:/home# bazel version
Build label: 3.1.0- (@non-git)
Build target: bazel-out/aarch64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jul 4 04:07:38 2020 (1593835658)
Build timestamp: 1593835658
Build timestamp as int: 1593835658
`
I don’t know if there is any problem, and then my tensorflow is also installed, and then I execute the` make tfa `command to install tensorflow-addons when there is a problem
`root@b39582782284:/home# make tfa
make: *** No rule to make target 'tfa'.  Stop.
`
Do I need to perform any pre-operations when I execute `make tfa`?

**Comment by koenvervloesem** [comment]
I guess you were in the wrong directory. Have you solved this (seeing your comment in https://github.com/koenvervloesem/rasa-docker-arm/issues/1#issuecomment-726555786)?

**Comment by karmalk** [comment]
I solved this tensorflow-addons problem. I went directly to tensorflow github to find the source code and directly pip install *.tar.gz. But I can’t install version 0.7.1, I can only install version 0.11 successfully, but rasa 1.10 only supports version 0.7 of tensorflow-addons, so I try to use rasa 2.0 to solve
